# Generated by Django 5.2.4 on 2025-10-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.TextField(verbose_name='Nội dung lựa chọn'),
        ),
    ]
