# Generated by Django 5.2.4 on 2025-10-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_choice_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.AddField(
            model_name='question',
            name='search_acronym',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, default='', verbose_name='Diễn giải'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Thứ tự'),
        ),
    ]
