# Generated by Django 5.2.4 on 2025-10-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_question_options_question_search_acronym_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='search_text_normalized',
            field=models.TextField(blank=True, db_index=True, editable=False, verbose_name='Nội dung chuẩn hóa'),
        ),
    ]
